"""Stage D: reference-image generation (Qwen-Image + depth ControlNet), RMBG cutout, scoring.

The reference image is generated by the Qwen-Image 20B MMDiT base model conditioned on the
mesh's rendered depth map through the InstantX Qwen-Image ControlNet-Union adapter (depth
mode): depth locks silhouette + coarse 3D while leaving surface appearance free. The 20B DiT
plus its 7B text encoder exceed a single A40, so the pipeline runs with model CPU offload
(one module resident at a time). Runs in the `trellis2` (primary) env.
"""
from __future__ import annotations

import gc
import hashlib
import json
import sys
from pathlib import Path
from typing import Optional

import numpy as np
import torch
from PIL import Image

from pbr_texture_pipeline.config import load_config

_CFG = load_config()
# TRELLIS.2 on sys.path so we can reuse its BiRefNet rembg wrapper (identical cutout).
_TRELLIS_REPO = str(_CFG.repo("trellis2"))
if _TRELLIS_REPO not in sys.path:
    sys.path.insert(0, _TRELLIS_REPO)

_QWEN = _CFG.model("qwen_image")
_CN = _CFG.model("controlnet")

_pipe = None
_pipe_key: Optional[str] = None
_rmbg = None
_clip = None  # lazy; may stay None if no CLIP weights (see clip_score)


# --- ControlNet + Qwen-Image load (Task 3.1) ---------------------------------
def _load_controlnet():
    from diffusers import QwenImageControlNetModel

    # InstantX Qwen-Image ControlNet-Union: one adapter covering canny/soft-edge/depth/pose.
    # pbr-texture-pipeline drives its depth mode by passing the rendered depth map as the control image.
    return QwenImageControlNetModel.from_pretrained(_CN, torch_dtype=torch.bfloat16)


def load_pipe(kind: str = "depth", use_union: bool = False):
    """Load (or return cached) Qwen-Image ControlNet pipeline.

    `kind`/`use_union` are retained for call-site compatibility, but only depth is used:
    the Qwen ControlNet-Union takes a single control image at a time, so the old SDXL
    depth+canny dual-control path does not apply here.
    """
    global _pipe, _pipe_key
    key = "qwen-depth"
    if _pipe is not None and _pipe_key == key:
        return _pipe
    if _pipe is not None:
        unload_pipe()
    from diffusers import QwenImageControlNetPipeline

    if kind == "depth+canny" or use_union:
        print("[diffusion] note: Qwen ControlNet-Union takes one control image; using depth only")
    controlnet = _load_controlnet()
    print("[diffusion] loading Qwen-Image + ControlNet (depth) bf16 ...")
    pipe = QwenImageControlNetPipeline.from_pretrained(
        _QWEN, controlnet=controlnet, torch_dtype=torch.bfloat16)
    # 20B DiT + 7B text encoder exceed one A40 (46 GB); stream modules on demand.
    pipe.enable_model_cpu_offload()
    _pipe, _pipe_key = pipe, key
    print("[diffusion] Qwen-Image pipeline ready")
    return _pipe


def unload_pipe():
    global _pipe, _pipe_key
    if _pipe is not None:
        del _pipe
        _pipe = None
        _pipe_key = None
        gc.collect()
        torch.cuda.empty_cache()


def unload_scoring_models():
    """Free RMBG + CLIP from VRAM (they lazy-reload on the next score/cutout).

    The 20B DiT forward peaks ~40 GB; on a 46 GB card the ~3 GB these two hold is the margin
    between a clean multi-job Stage D run and an OOM, so the batch loop drops them before
    each job's candidate generation.
    """
    global _rmbg, _clip
    if _rmbg is not None:
        del _rmbg
        _rmbg = None
    if _clip not in (None, "unavailable"):
        del _clip
        _clip = None
    gc.collect()
    torch.cuda.empty_cache()


def _control_rgb(path: Path) -> Image.Image:
    """Control maps are saved grayscale L; ControlNet wants 3-channel RGB."""
    return Image.open(path).convert("RGB")


def _prompt_hash(prompt: str) -> str:
    return hashlib.sha1(prompt.encode()).hexdigest()[:12]


# --- candidate generation (Task 3.1) -----------------------------------------
def generate_candidates(
    jobdir,
    prompt: str,
    negative_prompt: str,
    base_seed: int,
    n: int = 4,
    cn_scale: Optional[float] = None,
    canny_scale: Optional[float] = None,
    guidance: Optional[float] = None,
    steps: Optional[int] = None,
    kind: str = "depth",
    use_union: bool = False,
) -> list[dict]:
    """Generate n candidates (seeds base_seed+i, batch 1) into ref/. Returns sidecar dicts.

    `guidance` maps to Qwen-Image's `true_cfg_scale` (real classifier-free guidance; the
    negative prompt only takes effect when it is > 1). `canny_scale` is accepted but unused
    (the Qwen ControlNet-Union conditions on a single depth image).
    """
    cn_scale = _CFG.get("diffusion.cn_scale") if cn_scale is None else cn_scale
    guidance = _CFG.get("diffusion.guidance") if guidance is None else guidance
    steps = _CFG.get("diffusion.steps") if steps is None else steps
    w, h = int(_CFG.get("diffusion.width")), int(_CFG.get("diffusion.height"))

    pipe = load_pipe(kind, use_union)
    control_image = _control_rgb(jobdir.control("depth"))

    sidecars = []
    for i in range(n):
        seed = base_seed + i
        gen = torch.Generator(device="cuda").manual_seed(seed)
        image = pipe(
            prompt=prompt, negative_prompt=negative_prompt,
            control_image=control_image, controlnet_conditioning_scale=float(cn_scale),
            num_inference_steps=int(steps), true_cfg_scale=float(guidance),
            height=h, width=w, generator=gen,
        ).images[0]
        image.save(jobdir.candidate(i))
        side = {
            "index": i, "seed": seed, "prompt_hash": _prompt_hash(prompt),
            "cn_scale": float(cn_scale), "true_cfg_scale": float(guidance),
            "steps": int(steps), "controlnet": "qwen-union-depth",
        }
        jobdir.write_json(jobdir.candidate_sidecar(i), side)
        sidecars.append(side)
        print(f"[diffusion] candidate {i} (seed {seed}) -> {jobdir.candidate(i).name}")
    return sidecars


def next_base_seed(current_base: int, n: int = 4) -> int:
    """Reroll bumps base_seed by n (PRD section 5)."""
    return current_base + n


def generate_open_reference(jobdir, base_seed: int, index: int) -> Path:
    """Open-pose reference for articulated global texture mode (PRD_articulated_v2).

    One Qwen-Image generation conditioned on control/open/depth.png with the same prompt,
    negative prompt, and seed as the selected rest-pose candidate (base_seed + index), plus
    its RMBG cutout. Writes its own artifacts (ref/generated_open/, ref/chosen_rgba_open.png)
    and reuses the loaded pipe/RMBG; the rest-pose candidate flow is untouched. No scoring
    or selection: the rest-pose choice already fixed the style.
    """
    spec = jobdir.read_json(jobdir.spec())
    prompt, negative = spec["ref_prompt"], spec.get("negative_prompt", "")
    cn_scale = float(_CFG.get("diffusion.cn_scale"))
    guidance = float(_CFG.get("diffusion.guidance"))
    steps = int(_CFG.get("diffusion.steps"))
    w, h = int(_CFG.get("diffusion.width")), int(_CFG.get("diffusion.height"))

    depth_path = jobdir.path("control", "open", "depth.png")
    if not depth_path.is_file():
        raise FileNotFoundError(f"{depth_path} missing; re-run Stage R")
    # The rest-pose selection just ran score + cutout, so RMBG/CLIP are resident; the 20B
    # forward needs that ~3 GB back or it OOMs on a 46 GB card (same margin as the batch
    # loop's pre-candidate unload). RMBG lazy-reloads for the cutout below.
    unload_scoring_models()
    pipe = load_pipe("depth")
    control_image = _control_rgb(depth_path)
    seed = int(base_seed) + int(index)
    gen = torch.Generator(device="cuda").manual_seed(seed)
    image = pipe(
        prompt=prompt, negative_prompt=negative,
        control_image=control_image, controlnet_conditioning_scale=cn_scale,
        num_inference_steps=steps, true_cfg_scale=guidance,
        height=h, width=w, generator=gen,
    ).images[0]

    out_dir = jobdir.path("ref", "generated_open")
    out_dir.mkdir(parents=True, exist_ok=True)
    image.save(out_dir / "chosen.png")
    jobdir.write_json(out_dir / "chosen.json", {
        "seed": seed, "rest_candidate_index": int(index), "prompt_hash": _prompt_hash(prompt),
        "cn_scale": cn_scale, "true_cfg_scale": guidance, "steps": steps,
        "controlnet": "qwen-union-depth", "control": str(depth_path),
    })

    rmbg = _load_rmbg()
    rgba = rmbg(image.convert("RGB").copy())
    rgba_path = jobdir.path("ref", "chosen_rgba_open.png")
    rgba.save(rgba_path)
    print(f"[diffusion] open-pose reference (seed {seed}) -> {rgba_path.name}")
    return rgba_path


# --- RMBG cutout (Task 3.2) --------------------------------------------------
def _load_rmbg():
    global _rmbg
    if _rmbg is not None:
        return _rmbg
    from trellis2.pipelines.rembg import BiRefNet  # reuse TRELLIS.2's wrapper

    print(f"[diffusion] loading RMBG ({_CFG.model('rmbg')}) ...")
    _rmbg = BiRefNet(_CFG.model("rmbg"))
    _rmbg.cuda()
    return _rmbg


def cutout(jobdir, candidate_index: int) -> Path:
    """RMBG-2.0 cutout of the chosen candidate -> chosen.png (RGB) + chosen_rgba.png (alpha).

    The RGBA is what the backends receive; TRELLIS.2 preprocess_image uses this alpha directly
    and never re-runs rembg, so the cutout is identical everywhere (PRD section 5).
    """
    src = jobdir.candidate(candidate_index)
    rgb = Image.open(src).convert("RGB")
    rgb.save(jobdir.chosen())  # RGB as generated

    rmbg = _load_rmbg()
    rgba = rmbg(rgb.copy())  # returns RGBA with predicted alpha
    rgba.save(jobdir.chosen_rgba())
    return jobdir.chosen_rgba()


def _alpha_mask(rgba_path: Path, thresh: float = 0.5) -> np.ndarray:
    a = np.asarray(Image.open(rgba_path).convert("RGBA"))[:, :, 3].astype(np.float32) / 255.0
    return a > thresh


# --- scoring + selection (Task 3.3) ------------------------------------------
def silhouette_iou(rgba_path: Path, control_mask_path: Path) -> float:
    """IoU(RMBG cutout alpha mask, control/mask.png), resized to the control resolution."""
    cut = _alpha_mask(rgba_path)
    ctrl = np.asarray(Image.open(control_mask_path).convert("L")) > 127
    if cut.shape != ctrl.shape:
        cut_img = Image.fromarray((cut * 255).astype(np.uint8)).resize(
            (ctrl.shape[1], ctrl.shape[0]), Image.NEAREST)
        cut = np.asarray(cut_img) > 127
    inter = np.logical_and(cut, ctrl).sum()
    union = np.logical_or(cut, ctrl).sum()
    return float(inter / union) if union else 0.0


def clip_score(prompt: str, image_path: Path) -> Optional[float]:
    """CLIP(prompt, image) cosine similarity, or None if no CLIP weights are available.

    Uses transformers CLIPModel lazily; returns None (caller falls back to IoU-only) if the
    weights are not present, so selection never hard-fails on a missing optional model.
    """
    global _clip
    if _clip == "unavailable":
        return None
    try:
        if _clip is None:
            from transformers import CLIPModel, CLIPProcessor
            repo = _CFG.get("models.clip", "openai/clip-vit-large-patch14")
            model = CLIPModel.from_pretrained(repo).to("cuda").eval()
            proc = CLIPProcessor.from_pretrained(repo)
            _clip = (model, proc)
    except Exception as e:  # noqa: BLE001
        print(f"[diffusion] CLIP unavailable ({e}); selection falls back to IoU-only.")
        _clip = "unavailable"
        return None
    model, proc = _clip
    img = Image.open(image_path).convert("RGB")
    inputs = proc(text=[prompt], images=[img], return_tensors="pt", padding=True,
                  truncation=True).to("cuda")
    with torch.no_grad():
        out = model(**inputs)
        ie = out.image_embeds / out.image_embeds.norm(dim=-1, keepdim=True)
        te = out.text_embeds / out.text_embeds.norm(dim=-1, keepdim=True)
        return float((ie * te).sum(dim=-1)[0])


def score_candidates(jobdir, prompt: str, n: int = 4) -> list[dict]:
    """Score every candidate by silhouette IoU (+ CLIP if available). RMBG runs per candidate."""
    rmbg = _load_rmbg()
    ctrl_mask = jobdir.control("mask")
    scores = []
    for i in range(n):
        cand = jobdir.candidate(i)
        rgba = rmbg(Image.open(cand).convert("RGB"))
        tmp = jobdir.path("ref", f"_cutmask_{i:02d}.png")
        rgba.save(tmp)
        iou = silhouette_iou(tmp, ctrl_mask)
        clip = clip_score(prompt, cand)
        scores.append({"index": i, "iou": iou, "clip": clip})
        print(f"[diffusion] candidate {i}: IoU={iou:.3f} CLIP={clip}")
    return scores


def select_batch(scores: list[dict], iou_threshold: Optional[float] = None) -> dict:
    """Batch policy: filter IoU>=thr, pick max CLIP; if all fail, max-IoU + needs_review.

    Returns {"index": int, "needs_review": bool, "reason": str}.
    """
    thr = _CFG.get("select.iou_threshold") if iou_threshold is None else iou_threshold
    passing = [s for s in scores if s["iou"] >= thr]
    if passing:
        have_clip = all(s["clip"] is not None for s in passing)
        key = (lambda s: (s["clip"] if s["clip"] is not None else -1)) if have_clip else (lambda s: s["iou"])
        best = max(passing, key=key)
        return {"index": best["index"], "needs_review": False,
                "reason": ("max CLIP among IoU-pass" if have_clip else "max IoU (no CLIP)")}
    best = max(scores, key=lambda s: s["iou"])
    return {"index": best["index"], "needs_review": True,
            "reason": f"all candidates below IoU {thr}"}
